ORAL_PHENOTYPES = ["Temporomandibular joint disorders",
                   "Diseases and other conditions of the tongue",
                   "Dysphagia",
                   "Congenital anomalies of the eye",
                   "Periodontitis (acute or chronic)",
                   "Voice disturbance",
                   "Cancer of mouth",
                   "Congenital anomalies of skull and face bones",
                   "Glossitis",
                   "Benign neoplasm of lip, oral cavity, and pharynx",
                   "Congenital osteodystrophies",
                   "Sialolithiasis",
                   "Disturbances in tooth eruption",
                   "Diseases of the oral soft tissues, excluding lesions specific for gingiva and tongue",
                   "Facial weakness",
                   "Diseases of lips",
                   "Skull and face fracture and other intercranial injury",
                   "Benign neoplasm of pituitary gland and craniopharyngeal duct (pouch)",
                   "Disturbances of sensation of smell and taste",
                   "Otitis externa",
                   "Perforation of tympanic membrane",
                   "Septal Deviations/Turbinate Hypertrophy",
                   "Aphasia/speech disturbance",
                   "Acute and chronic tonsillitis",
                   "Stomatitis and mucositis",
                   "Diseases of the jaws",
                   "Open wound of lip and mouth",
                   "Other open wound of head and face",
                   "Open wounds of head; neck; and trunk",
                   "Throat pain",
                   "Anomalies of jaw size/symmetry",
                   "Gingivitis",
                   "Anomalies of tooth position/malocclusion",
                   "Cleft palate",
                   "Cysts of the jaws",
                   "Inflammatory conditions of jaw",
                   "Leukoplakia of oral mucosa",
                   "Jaw disease NOS",
                   "Open wound of nose and sinus",
                   "Speech and language disorder",
                   "Dental caries",
                   "Cancer of tongue",
                   "Diseases of hard tissues of teeth",
                   "Dental abrasion, erosion and attrition",
                   "Broken tooth"]

COLORS = {"Overall": "#1e88e5", "Indicated": "#d81b60", "Spontaneous": "#fe6100", "Term": "#FFB000"}
IND_SIG_ROBUST = ["Complications of transplants and reattached limbs",
                  "Nonspecific abnormal findings on radiological and other examination of other intrathoracic organs (echocardiogram, etc)",
                  "Edema",
                  "Lupus (localized and systemic)",
                  "Pelvic peritoneal adhesions, female (postoperative) (postinfection)",
                  "Other nonspecific findings on examination of urine",
                  "Kidney replaced by transpant",
                  "Other disorders of the kidney and ureters",
                  "Chronic kidney disease, Stage I or II",
                  "Chronic renal failure [CKD]",
                  "Nephritis and nephropathy without mention of glomerulonephritis",
                  "Other disorders of liver",
                  "Other chronic nonalcoholic liver disease",
                  "Abnormal findings examination of lungs",
                  "Other diseases of lung",
                  "Acute laryngitis and tracheitis",
                  "Congestive heart failure (CHF) NOS",
                  "Cardiomegaly",
                  "Other hypertensive complications",
                  "Hypertensive heart and/or renal disease",
                  "Essential hypertension",
                  "Decreased white blood cell count",
                  "Anemia of chronic disease",
                  "Other anemias",
                  "Acid-base balance disorder",
                  "Electrolyte imbalance",
                  "Disorders of magnesium metabolism",
                  "Proteinuria",
                  "Type 2 diabetes",
                  "Type 1 diabetes"]
OVERALL_SIG_ROBUST = ["Pelvic peritoneal adhesions, female (postoperative) (postinfection)",
                      "Kidney replaced by transpant",
                      "Other disorders of the kidney and ureters",
                      "Chronic kidney disease, Stage I or II",
                      "Chronic renal failure [CKD]",
                      "Nephritis and nephropathy without mention of glomerulonephritis",
                      "Other disorders of liver",
                      "Other diseases of lung",
                      "Cardiomegaly",
                      "Hypertensive heart and/or renal disease",
                      "Essential hypertension",
                      "Disease of tricuspid valve",
                      "Decreased white blood cell count",
                      "Anemia of chronic disease",
                      "Acid-base balance disorder",
                      "Proteinuria",
                      "Type 2 diabetes",
                      "Type 1 diabetes"]  #100%
IND_SIG_ROBUST_NO_OUTLIERS = IND_SIG_ROBUST.copy()
IND_SIG_ROBUST_NO_OUTLIERS.remove("Acute laryngitis and tracheitis")
IND_SIG_ROBUST_NO_OUTLIERS.remove("Congestive heart failure (CHF) NOS")
